### ISSUE TITLE
Xcode 12+ fails to build Example app for both simulator and device

### ISSUE THREAD

**Issue by magicwave** [roam-ai/roam-ios#1]
Xcode 12.5 displays this error when running a build for either device or simulator: 
"Building for iOS Simulator, but the linked and embedded framework 'Roam.framework' was built for iOS + iOS Simulator."

This appears to require building an XCFramework by the third party, i.e. Roam.ai.

These links may be instructive:  
- https://stackoverflow.com/questions/65303304/xcode-12-3-building-for-ios-simulator-but-the-linked-and-embedded-framework-wa. 
- https://help.apple.com/xcode/mac/current/#/dev544efab96

**Comment by ravikanth-tummala** [comment]
@magicwave 
Build Setting tab -> **Validate Workspace** to **Yes** 

<img width="688" alt="Screenshot 2021-06-17 at 12 39 26 PM" src="https://user-images.githubusercontent.com/43139135/122348839-33a68980-cf69-11eb-8fb2-d7c1d21094ac.png">

**Comment by magicwave** [comment]
Failed. I ensured that the Pods target setting was the same for Validate Workspace as well. Note in the attachment, besides the Build Phase script error, the fat framework warning persists.
<img width="1533" alt="Build-fail_2021-06-17" src="https://user-images.githubusercontent.com/10930016/122587940-53928780-d013-11eb-99de-124634f5bd21.png">

**Comment by ravikanth-tummala** [comment]
@magicwave  can you make sure set for Target
**Targets ->Build Setting -> Validate Workspace to Yes**

**Comment by manojadithya** [comment]
@magicwave i assume this is fixed. Can I close the issue?

**Comment by magicwave** [comment]
Not fixed. Both the project and target build settings Validate Workspace were set to Yes. I gave up trying to get the Example app to build and focused on trying to get basic interaction with the SDK. This also failed: see [issue #2](https://github.com/roam-ai/roam-ios/issues/2)

Various documentation resources are confusing and incompatible. We were able to get the Android SDK to do tracking but continue to fail with iOS SDK.

Thanks for being responsive.

**Comment by manojadithya** [comment]
@magicwave the roam-iOS SDK is still an experimental update as it’s part of rebranding from GeoSpark to Roam. To use a more stable version of SDK we recommend using our GeoSpark iOS SDK version 3.1.6. You’ll find the docs on our official docs page: https://docs.roam.ai/ios/quickstart-1

**Comment by magicwave** [comment]
Will the GeoSpark SDK work for an existing Roam project?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Manoj Adithya ***@***.***>
Sent: Tuesday, June 22, 2021 12:31:12 AM
To: roam-ai/roam-ios ***@***.***>
Cc: Eric Turner ***@***.***>; Mention ***@***.***>
Subject: EXT:Re: [roam-ai/roam-ios] Xcode 12+ fails to build Example app for both simulator and device (#1)


@magicwave<https://github.com/magicwave> the roam-iOS SDK is still an experimental update as it’s part of rebranding from GeoSpark to Roam. To use a more stable version of SDK we recommend using our GeoSpark iOS SDK version 3.1.6. You’ll find the docs on our official docs page: https://docs.roam.ai/ios/quickstart-1

**Comment by manojadithya** [comment]
Yes, it will work.

**Comment by magicwave** [comment]
The official docs for GeoSpark SDK v3.1.6 are the same as for Roam SDK: confusing and incompatible in some particulars.

I was unable to get the GeoSpark SDK to build for iPhone 7 device. (see [GeoSpark repo issue #3](https://github.com/geosparks/geospark-sdk-ios/issues/new))

**Comment by jothipriyadharshanr** [comment]
Fixed in https://github.com/roam-ai/roam-ios/releases/tag/0.0.7
Fix added to [GeoSpark repo issue #3](https://github.com/geosparks/geospark-sdk-ios/issues/new)
